version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      - h2-console

  h2-console:
    image: h2database/h2-console
    ports:
      - "8082:8082"
    environment:
      - H2_DATABASE_TO_UPPER=false